version: '3'

services:
  app:
    build: ./
    ports:
      - "80:8080"
    depends_on:
      - mypostgres

  mypostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=paymentsapi
